name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  render-tutorials:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: render tutorial in projects/noj
      uses: devcontainers/ci@v0.3
      with:    
               subFolder: projects/noj
               push: never
               runCmd: clj notebooks/render.clj

    # - name: render tutorial in projects/data-processing
    #   uses: devcontainers/ci@v0.3
    #   with:    
    #            subFolder: projects/data-processing
    #            push: never
    #            runCmd: clj notebooks/render.clj

    - name: render tutorial in projects/datavis/python/plotting
      uses: devcontainers/ci@v0.3
      with:    
               subFolder: projects/datavis/python/plotting
               push: never
               runCmd: clj -Adev notebooks/render.clj
               
    - name: render tutorial in projects/datavis/ggplot
      uses: devcontainers/ci@v0.3
      with:    
               subFolder: projects/datavis/ggplot
               push: never
               runCmd: clj -Adev notebooks/render.clj


    - name: clean docs
      run: |
         rm -rf docs/*.*

    - name: combine all tutorials
      uses: tzafrirben/babashka-docker-action@v1.1
      with:
         bb_src: make_docs.clj


    - name: Prepare java
      uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: 1.10.1.693 


    - name: fix permisions
      run: sudo chmod o+w docs/

    - name: check permisison
      run: |
         ls -la docs/
      
    - name: create main index
      run: clojure notebooks/render_index.clj 


    - name: check git status
      run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          ls docs/projects
          git status


    - name: push updated docs
      uses: stefanzweifel/git-auto-commit-action@v5
     
                         
